economic_data_api:
  url: "http://api.worldbank.org/v2/country/all/indicator/NY.GDP.MKTP.CD"
  params: 
    format: "json"
    per_page: 1000

crop_yield_data_html:
  url: "https://www.indexmundi.com/agriculture/?commodity=wheat&graph=yield"
